//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class FurnitureStock
    {
        public int Id { get; set; }
        public string IdFurniture { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<int> IdUnitWidth { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<int> IdUnitHeight { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
    
        public virtual Furniture Furniture { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
    }
}
