
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SewingCompany
{

using System;
    using System.Collections.Generic;
    
public partial class OrderList
{

    public int Id { get; set; }

    public int IdOrder { get; set; }

    public string IdProduct { get; set; }

    public string IdFabric { get; set; }

    public string IdFurniture { get; set; }



    public virtual Fabric Fabric { get; set; }

    public virtual Furniture Furniture { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

}

}
