
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SewingCompany
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    public int Id { get; set; }

    public int IdUser { get; set; }

    public System.DateTime Date { get; set; }

    public int IdState { get; set; }

    public Nullable<int> IdManager { get; set; }



    public virtual OrderState OrderState { get; set; }

    public virtual User User { get; set; }

}

}
