//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SewingCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrapRule
    {
        public int Id { get; set; }
        public string IdMaterial { get; set; }
        public int IdUnit { get; set; }
        public int Value { get; set; }
    
        public virtual Fabric Fabric { get; set; }
    }
}
